version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.0.111:8080
functions:
  sensorsettings:
    lang: python3-http-debian
    handler: ./sensorsettings
    image: gustavoasc/sensorsettings:latest

